In [2]:
import numpy as np
import time

In [3]:
# Method of generating a positive semidefinite matrix
# 1. Generate a random square matrix
# 2. multiply it by its own transposition
# 3. we have obtained a positive semi-definite matrix.

def generateRandomPositiveSemidefiniteMatrix(size, scaleDown):
    randomMatrix = np.random.rand(size, size)
    positive_semidefinite_matrix = np.matmul(randomMatrix, randomMatrix.transpose()) / scaleDown
    return positive_semidefinite_matrix

# Generate linearly spacing vector from 1 to size for x*
def generateLinearOptimalX(size):
    return np.arange(1, size + 1, 1).astype(int)

# A matrix is positive semidefinite if all of its eigenvalues are nonnegative
# Note: this matrix should be symmetric
def isPositiveSemidefinite(A):
    return np.all(np.linalg.eigvals(A) >= 0)

# A matrix does not have an inverse if its determinant is equal to 0
def inverse(A):
    return np.linalg.inv(A)

In [11]:
# scale = "small"
scale = "large"
# scale = "huge"

if scale == "small":
    size = 10
    scaleDown = 1
elif scale == "large":
    size = 100
    scaleDown = 10
elif scale == "huge":
    size = 1000
    scaleDown = 100

start = time.time()
A = generateRandomPositiveSemidefiniteMatrix(size, scaleDown)
end = time.time()


print("The matrix A is")
print(A)

print("\nTime required to generate the matrix A is")
print(f"{end - start} seconds")

# print(f"Is the matrix A positive semidefinite?: {isPositiveSemidefinite(A)}")

start = time.time()
invA = inverse(A)
end = time.time()

print("\nThe inverse of matrix A is")
print(invA)

print("\nTime required to inverr the matrix A is")
print(f"{end - start} seconds")

# invA = np.array([[ 0.0824827, 0.01241379, -0.0377931],
#                  [ 0.0124137, 0.06206897, 0.01103448],
#                  [-0.0377931, 0.01103448, 0.07751724]])

# The optimal solution
x_opt = generateLinearOptimalX(size)
print("\nThe optimal solution x* is")
print(x_opt)

# b is in the range of A
# In other words, b is a linear combination of the columns of matrix A
b = A.dot(x_opt)
print("\nThe vector b is")
print(b)

# So we have the identities:
# Ax* = b or Ax - b = 0
# A^-1b = x*

# print("\nAx* should be equal to b") 
# print(A.dot(x_opt))

# print("\nA^-1b should be equal to x*") 
# print(invA.dot(b))

np.save(f"{scale}Matrix.npy", A)
np.save(f"{scale}Vector.npy", b)
np.save(f"{scale}Solution.npy", x_opt)

The matrix A is
[[3.43473025 2.93675439 2.58198327 ... 2.31585303 2.45632002 2.49678301]
 [2.93675439 3.98292537 2.71844624 ... 2.66301381 2.75347921 2.58784132]
 [2.58198327 2.71844624 3.53397275 ... 2.38790868 2.45556549 2.39003511]
 ...
 [2.31585303 2.66301381 2.38790868 ... 2.99265261 2.40306941 2.19187246]
 [2.45632002 2.75347921 2.45556549 ... 2.40306941 3.21836133 2.33970393]
 [2.49678301 2.58784132 2.39003511 ... 2.19187246 2.33970393 2.92906891]]

Time required to generate the matrix A is
0.0010180473327636719 seconds

The inverse of matrix A is
[[  959.34322187  1079.03838448 -1567.2199227  ...   757.65160595
   2473.63047512 -2877.5843806 ]
 [ 1079.03838448  1314.25849817 -1825.53662524 ...   917.945272
   2900.61723272 -3430.86480538]
 [-1567.2199227  -1825.53662524  2640.73200815 ... -1263.23088866
  -4152.29414217  4820.9020362 ]
 ...
 [  757.65160595   917.945272   -1263.23088866 ...   691.03835987
   1995.88028498 -2432.89302846]
 [ 2473.63047512  2900.61723272 -4152.29