In [1]:
import numpy as np
differenceNorms = np.array([16,11,7,4,2,1])
errors = np.abs(np.diff(differenceNorms))
print(errors)
errors_nminus1 = errors[:-2]
print(errors_nminus1)
errors_n = errors[:-1]
errors_n = errors_n[1:]
print(errors_n)
errors_nplus1 = errors[2:]
print(errors_nplus1)

rateOfConvergences = np.divide(np.log(np.abs(np.divide(errors_nplus1, errors_n))), np.log(np.abs(np.divide(errors_n, errors_nminus1))))

print(rateOfConvergences)


print(np.seterr())

array = np.array([1,2,3,4,5])
array[1] = -1
print(array)

[5 4 3 2 1]
[5 4 3]
[4 3 2]
[3 2 1]
[1.28922423 1.40942084 1.70951129]
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
[ 1 -1  3  4  5]


In [ ]:
A = np.array([[17, -5, 9],
              [-5, 18, -5],
              [9, -5, 18]])

print("The matrix A is")
print(A)

print(f"Is the matrix A positive semidefinite?: {isPositiveSemidefinite(A)}")

invA = inverse(A)
print("\nThe inverse of matrix A is")
print(invA)

# invA = np.array([[ 0.0824827, 0.01241379, -0.0377931],
#                  [ 0.0124137, 0.06206897, 0.01103448],
#                  [-0.0377931, 0.01103448, 0.07751724]])

# The optimal solution
x_opt = np.array([1,2,3])  
print("\nThe optimal solution x* is")
print(x_opt)

# b is in the range of A
# In other words, b is a linear combination of the columns of matrix A
# b = A.dot(x_opt)
b = np.array([34,16,53]) 
print("\nThe vector b is")
print(b)

# So we have the identities:
# Ax* = b or Ax - b = 0
# A^-1b = x*

print("\nAx* should be equal to b") 
print(A.dot(x_opt))

print("\nA^-1b should be equal to x*") 
print(invA.dot(b))

The matrix A is
[[17 -5  9]
 [-5 18 -5]
 [ 9 -5 18]]
Is the matrix A positive semidefinite?: True

The inverse of matrix A is
[[ 0.08248276  0.01241379 -0.0377931 ]
 [ 0.01241379  0.06206897  0.01103448]
 [-0.0377931   0.01103448  0.07751724]]

The optimal solution x* is
[1 2 3]

The vector b is
[34 16 53]

Ax* should be equal to b
[34 16 53]

A^-1b should be equal to x*
[1. 2. 3.]
